# Generated by Django 2.1.5 on 2019-02-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='cart',
        ),
    ]
