# Generated by Django 2.1.5 on 2019-02-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
