# Generated by Django 2.1.5 on 2019-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190207_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='products', through='shop.CartProduct', to='shop.Cart'),
        ),
    ]
