# Generated by Django 2.1.5 on 2019-02-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='groups',
            new_name='carts',
        ),
    ]
