# Generated by Django 2.1.5 on 2019-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190207_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('full_path',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
